export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SEARCH_INGREDIENTS = "SEARCH_INGREDIENTS";
export const CLEAR_SELECTED_INGREDIENTS = 'CLEAR_SELECTED_INGREDIENTS';